### PR TITLE
Fix error on android targeting S+

### PR DESCRIPTION
**Pull request by hans00**

### CODE REVIEW

**Comment by flyskywhy** [comment]
Many IoT devices (include mine) with USB run in low version of Android e.g. 7.0, so I have no enviroment to test this PR.

Could you describe some info of your use case? (before I merge your PR 😝  )

**Comment by hans00** [comment]
Our product is for consumer usage, which may include higher version.
I tested on Android 12 (Samsung Tablet S6).

Without this PR will throw error:
```
Connection Failed! Catch Error Message:com.brickslauncherbeta: Targeting S+ (version 31 and above) requires that one of FLAG IMMUTABLE or FLAG MUTABLE be specified when creating a PendingIntent. Strongly consider using FLAG IMMUTABLE, only use FLAG MUTABLE if some functionality depends on the Pendingintent being mutable, e.g. if it needs to be used with inline replies or bubbles.
```

**Comment by flyskywhy** [comment]
Thanks, and another question, If you are compiling for Android 12, your gradle version may greater than `gradle-6.7.1`, so how do you solve the compile problem as described in https://github.com/flyskywhy/react-native-usb-serialport/blob/fad0ff4ad5aa9a64030e20a5fe6cdaa895a8a011/android/build.gradle#L51

**Comment by flyskywhy** [comment]
> Thanks, and another question, If you are compiling for Android 12, your gradle version may greater than `gradle-6.7.1`, so how do you solve the compile problem as described in
> 
> https://github.com/flyskywhy/react-native-usb-serialport/blob/fad0ff4ad5aa9a64030e20a5fe6cdaa895a8a011/android/build.gradle#L51

So I can describe your solution into `README.md`

**Comment by flyskywhy** [comment]
Resolved in `react-native-usb-serialport@3.0.0`

**Pull request merged**
